services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080
